### ISSUE TITLE
JS 裡的 let 、 const 、var 差在哪裡？

### ISSUE THREAD

**Issue by luofreddy** [luofreddy/blog#9]
```yaml
---
title: JS 裡的 let 、 const 、var 差在哪裡？
date: '2022-10-23'
tags: ['javascript']
draft: false
summary: 在 ES6 之前 javascript 的世界裡面只有 var 的宣告方式，而在 ES6 之後加上了 let 跟 const ，那這幾種宣告方式是差在哪裡呢？
---
```

## 前言
在 ES6 之前 javascript 的世界裡面只有 var 的宣告方式，而在 ES6 之後加上了 let 跟 const ，那這幾種宣告方式是差在哪裡呢？

## var ( Function-level scope )
當我們在用 var 宣告變數的時候這個變數就會是 Function-level scope ， 簡單來說 scope 的範圍就是以 function 作為範圍

```javascript
for (var i = 0; i < 3; i++) {
    console.log(i);  // 0, 1, 2
}

console.log(i);  // 3

/*------------------------------------------------*/

function varScope() {
    var myName = 'Freddy';
    console.log(myName);
}

console.log(myName);  // Uncaught ReferenceError: myName is not defined
```
## let 、 const ( Block-level scope )
在使用 let 、 const 宣告變數的時候則此變數就會是 Block-level scope ，也就是說變數的 scope 只會存在於 `{ }` 兩個大括號之間。

### let 、 const 差別
let 跟 const 的差異則是在能不能再次被更改。
```javascript
let myName = 'Freddy';
console.log(myName); // Freddy

myName = 'Tom';
console.log(myName); // Tom

/*------------------------------------------------*/

const myCat = 'OPA';
myCat = 'PiPi'; // Uncaught SyntaxError: Invalid or unexpected token
```javascript
for (var i = 0; i < 3; i++) {
    let hello = 'world';
    console.log(i);  // 0, 1, 2
}

console.log(hello); //Uncaught ReferenceError: hello is not defined
```
